### ISSUE TITLE
添加回调监控(宝塔环境) 报错

### ISSUE THREAD

**Issue by myitcloud** [v03413/epay_usdt#25]
root@instance-20240606-0459:~# /usr/bin/php /www/wwwroot/epay/plugins/usdt/cron.php 2
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to usdt_plugin::getTransferInList() must be of the type string, null given, called in /www/wwwroot/epay/plugins/usdt/usdt_plugin.php on line 83 and defined in /www/wwwroot/epay/plugins/usdt/usdt_plugin.php:99
Stack trace:
#0 /www/wwwroot/epay/plugins/usdt/usdt_plugin.php(83): usdt_plugin::getTransferInList()
#1 /www/wwwroot/epay/plugins/usdt/cron.php(21): usdt_plugin::cron()
#2 {main}
  thrown in /www/wwwroot/epay/plugins/usdt/usdt_plugin.php on line 99

Fatal error: Uncaught TypeError: Argument 1 passed to usdt_plugin::getTransferInList() must be of the type string, null given, called in /www/wwwroot/epay/plugins/usdt/usdt_plugin.php on line 83 and defined in /www/wwwroot/epay/plugins/usdt/usdt_plugin.php:99
Stack trace:
#0 /www/wwwroot/epay/plugins/usdt/usdt_plugin.php(83): usdt_plugin::getTransferInList()
#1 /www/wwwroot/epay/plugins/usdt/cron.php(21): usdt_plugin::cron()
#2 {main}
  thrown in /www/wwwroot/epay/plugins/usdt/usdt_plugin.php on line 99

**Comment by myitcloud** [comment]
易支付版本 
define('VERSION', '3075');
define('DB_VERSION', '2038');

**Comment by kk127686** [comment]
建议你用/www/server/php/74/bin/php
